char *multiply(char *s, char *r);
char *addition(char *s, char *r);
char *subtract(char *s, char *r);
char *add(char *x, char *y);
char *power(char *x, char *y);
int createint(char *y);
int compare(char *x, char *y);
char *divides(char *x, char *y);
char *comparison(char *x, char *y, char ch);
double createdouble(char *x);
char *sub(char *x, char *y);
char *mult(char *x, char *y);
char *division(char *x, char *y);
char *realadd(char *x, char *y);
char *realsub(char *x, char *y);
char *realmult(char *x, char *y);
//char *realpow(char *x, char *y);
char *realcomp(char *x, char *y, char ch);
char *realdiv(char *x, char *y);
char *remdec(char *ptr);
char *insertpt(char *x, int pos);
char *removezero(char *x);
char *addzerosbefore(char *x, int n);
char *addzerosafter(char *x, int n);
